import { expect } from 'chai';
import 'mocha';
import { InitialState, TopState, TraceLevel, makeHsm } from 'ihsm';

import { collectStatesFromExports, resolveStates } from '../discover';
import { generateTransitionTableModule } from '../generate';
import { planCartesianTransitions, planTransition } from '../plan';
import * as door from '../fixtures/door.machine';

describe('@ihsm/tools transition generator', () => {
	it('collects state classes from an exports namespace', () => {
		const refs = collectStatesFromExports(door.DoorTop, door);
		expect(refs.map(ref => ref.exportName).sort()).to.eql(['Closed', 'DoorTop', 'Open']);
	});

	it('plans a sibling transition (Closed → Open)', () => {
		const refs = resolveStates(door.DoorTop, { exports: door });
		const closed = refs.find(ref => ref.exportName === 'Closed')!;
		const open = refs.find(ref => ref.exportName === 'Open')!;
		const plan = planTransition(closed, open);
		expect(plan.key).to.equal('Closed=>Open');
		expect(plan.exit.map(ref => ref.exportName)).to.eql(['Closed']);
		expect(plan.entry.map(ref => ref.exportName)).to.eql(['Open']);
		expect(plan.finalState?.exportName).to.equal('Open');
		expect(plan.selfTransition).to.equal(false);
	});

	it('plans a self-transition with empty exit/entry', () => {
		const refs = resolveStates(door.DoorTop, { exports: door });
		const closed = refs.find(ref => ref.exportName === 'Closed')!;
		const plan = planTransition(closed, closed);
		expect(plan.selfTransition).to.equal(true);
		expect(plan.exit).to.eql([]);
		expect(plan.entry).to.eql([]);
		expect(plan.finalState).to.equal(undefined);
	});

	it('builds the cartesian product State × State', () => {
		const refs = resolveStates(door.DoorTop, { exports: door });
		const plans = planCartesianTransitions(refs);
		expect(plans).to.have.length(refs.length * refs.length);
	});

	it('generates routines that delegate to ihsm/transition-routines', () => {
		const source = generateTransitionTableModule({
			topState: door.DoorTop,
			exports: door,
			importPath: '../fixtures/door.machine',
		});
		expect(source).to.include('@generated by @ihsm/tools');
		expect(source).to.include("from 'ihsm/transition-routines'");
		expect(source).to.include('executeTransitionRoutine');
		expect(source).to.include('const plan_Closed_to_Open');
		expect(source).to.include('export function executeTransition');
		expect(source).to.include('TRANSITION_PLAN_COUNT =\n\t9 as const');
	});

	it('matches runtime transition traces for Closed → Open', async () => {
		const ctx: door.DoorCtx = { openCount: 0, trace: [] };
		const sm = makeHsm(door.DoorTop, ctx, true, TraceLevel.PRODUCTION);
		await sm.sync();

		const refs = resolveStates(door.DoorTop, { exports: door });
		const closed = refs.find(ref => ref.exportName === 'Closed')!;
		const open = refs.find(ref => ref.exportName === 'Open')!;
		const plan = planTransition(closed, open);

		sm.post('open');
		await sm.sync();

		for (const name of plan.exit.map(ref => `exit:${ref.exportName}`)) {
			expect(ctx.trace, `missing ${name}`).to.include(name);
		}
		for (const name of plan.entry.map(ref => `enter:${ref.exportName}`)) {
			expect(ctx.trace, `missing ${name}`).to.include(name);
		}
		expect(sm.currentState).to.equal(open.state);
	});
});
