/** Generated by scripts/generate-browser-test-entries.mjs — do not edit. */
import '../env.ts';
import * as chai from 'chai';

(globalThis as typeof globalThis & { expect: typeof chai.expect }).expect = chai.expect;

import '../../../examples/01-hello-state-machine/tutorial.spec.ts';
import '../../../examples/02-tracing/tutorial.spec.ts';
import '../../../examples/03-context/tutorial.spec.ts';
import '../../../examples/04-protocol-typing/tutorial.spec.ts';
import '../../../examples/05-hierarchy/tutorial.spec.ts';
import '../../../examples/07-internal-transitions/tutorial.spec.ts';
import '../../../examples/08-post-and-sync/tutorial.spec.ts';
import '../../../examples/09-deferred-post/tutorial.spec.ts';
import '../../../examples/10-call-services/tutorial.spec.ts';
import '../../../examples/11-restore/tutorial.spec.ts';
import '../../../examples/12-error-recovery/tutorial.spec.ts';
import '../../../examples/13-async-handlers/tutorial.spec.ts';
import '../../../examples/14-nested-machines/tutorial.spec.ts';
import '../../../examples/15-complex-workflow/tutorial.spec.ts';
import '../../../examples/17-post-now/tutorial.spec.ts';
import '../../../examples/shared/interactive.spec.ts';
import '../../../examples/testing-01-deferred-timers/tutorial.spec.ts';
import '../../../examples/testing-02-network-fetch/tutorial.spec.ts';
import '../../../examples/testing-03-event-streaming/tutorial.spec.ts';
import '../../../examples/testing-04-fault-injection/tutorial.spec.ts';
import '../../../examples/testing-05-subscriptions-and-disposables/tutorial.spec.ts';
