/** Generated by scripts/generate-browser-test-entries.mjs — do not edit. */
import '../env.ts';
import * as chai from 'chai';

(globalThis as typeof globalThis & { expect: typeof chai.expect }).expect = chai.expect;

import '../../../src/spec/actor-config.spec.ts';
import '../../../src/spec/cache.spec.ts';
import '../../../src/spec/coverage.spec.ts';
import '../../../src/spec/deadlock-guard.spec.ts';
import '../../../src/spec/decorator.spec.ts';
import '../../../src/spec/deferred.spec.ts';
import '../../../src/spec/error.default.spec.ts';
import '../../../src/spec/error.event.spec.ts';
import '../../../src/spec/error.initialization.spec.ts';
import '../../../src/spec/error.transition.spec.ts';
import '../../../src/spec/error.unhandled.spec.ts';
import '../../../src/spec/factory.spec.ts';
import '../../../src/spec/fields.spec.ts';
import '../../../src/spec/handler-dispatch.spec.ts';
import '../../../src/spec/internal-services.spec.ts';
import '../../../src/spec/makeHsm.spec.ts';
import '../../../src/spec/postNow.spec.ts';
import '../../../src/spec/process.spec.ts';
import '../../../src/spec/protocol-collision.spec.ts';
import '../../../src/spec/quote.spec.ts';
import '../../../src/spec/reserved-names.spec.ts';
import '../../../src/spec/restore.spec.ts';
import '../../../src/spec/runtime-coverage.spec.ts';
import '../../../src/spec/services-promise.spec.ts';
import '../../../src/spec/services.spec.ts';
import '../../../src/spec/state-names.spec.ts';
import '../../../src/spec/testing.spec.ts';
import '../../../src/spec/tracelevel.spec.ts';
import '../../../src/spec/transition.spec.ts';
