import fs from 'node:fs';
import path from 'node:path';

import { resolveStates } from './discover';
import { planCartesianTransitions, TransitionPlan } from './plan';

import type { GenerateTransitionTableOptions } from './generate-options';
export type { GenerateTransitionTableOptions } from './generate-options';

function planConstName(key: string): string {
	return `plan_${key.replace(/=>/g, '_to_')}`;
}

function formatTransitionKeyUnion(plans: TransitionPlan[]): string {
	if (plans.length === 0) {
		return '\tnever;';
	}
	return plans.map(plan => `\t'${plan.key}'`).join(' |\n');
}

function formatPlanConst(plan: TransitionPlan): string {
	const lines = [
		`const ${planConstName(plan.key)}: TransitionRoutinePlan = {`,
		`\texit: [${plan.exit.map(ref => ref.exportName).join(', ')}],`,
		`\tentry: [${plan.entry.map(ref => ref.exportName).join(', ')}],`,
	];
	if (plan.finalState !== undefined) {
		lines.push(`\tfinalState: ${plan.finalState.exportName},`);
	}
	lines.push(`\tfrom: ${plan.from.exportName},`, `\tto: ${plan.to.exportName},`, '};');
	return lines.join('\n');
}

function formatRoutine(plan: TransitionPlan): string {
	const params = 'instance, setCurrentState, hsm';
	const body = [
		`\t\texecuteTransitionRoutine(hsm, instance, ${planConstName(plan.key)}, ${plan.from.exportName}, ${plan.to.exportName}, {`,
		`\t\t\tstyle: 'production',`,
		`\t\t\tsetCurrentState,`,
		`\t\t}),`,
	].join('\n');
	return `\t'${plan.key}': (instance, setCurrentState, hsm) => {\n${body}\n\t},`;
}

/** Build the full TypeScript module source for a cartesian transition routine table. */
export function generateTransitionTableModule(options: GenerateTransitionTableOptions): string {
	const states = resolveStates(options.topState, options);
	const plans = planCartesianTransitions(states);
	const importNames = [...new Set(states.map(ref => ref.exportName))].sort((a, b) => a.localeCompare(b));
	const banner = options.banner ?? '@generated by @ihsm/tools — do not edit';

	const body = [
		`/** ${banner} */`,
		`import type { Any, State, StateClass } from 'ihsm';`,
		`import { executeTransitionRoutine, type TransitionRoutinePlan } from 'ihsm/transition-routines';`,
		`import { ${importNames.join(', ')} } from '${options.importPath}';`,
		'',
		'/** Actor instance (`_instance`) passed to lifecycle hooks via `.call(instance)`. */',
		'export type TransitionInstance = object;',
		'',
		'export type SetCurrentState = (state: StateClass<Any, undefined>) => void;',
		'',
		'export type TransitionRoutine = (',
		'\tinstance: TransitionInstance,',
		'\tsetCurrentState: SetCurrentState,',
		'\thsm: State<Any, undefined>,',
		') => void | Promise<void>;',
		'',
		'export const TRANSITION_STATE_EXPORTS = [',
		...importNames.map(name => `\t'${name}',`),
		'] as const;',
		'',
		...plans.map(formatPlanConst),
		'',
		'export type TransitionTableKey =',
		formatTransitionKeyUnion(plans),
		';',
		'',
		'/** Cartesian product — one executable routine per `from=>to` pair. */',
		'export const TRANSITION_ROUTINES: Record<TransitionTableKey, TransitionRoutine> = {',
		...plans.map(formatRoutine),
		'};',
		'',
		'export function executeTransition(',
		'\tkey: TransitionTableKey,',
		'\tinstance: TransitionInstance,',
		'\tsetCurrentState: SetCurrentState,',
		'\thsm: State<Any, undefined>,',
		'): void | Promise<void> {',
		'\treturn TRANSITION_ROUTINES[key](instance, setCurrentState, hsm);',
		'}',
		'',
		'export const TRANSITION_PLAN_COUNT =',
		`\t${plans.length} as const;`,
		'',
	].join('\n');

	return `${body}\n`;
}

/** Write a generated transition table module to `outputPath`. */
export function writeTransitionTableFile(outputPath: string, options: GenerateTransitionTableOptions): void {
	const source = generateTransitionTableModule(options);
	fs.mkdirSync(path.dirname(outputPath), { recursive: true });
	fs.writeFileSync(outputPath, source, 'utf8');
}
